/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/l5XqPf6yuGB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex h-screen w-full overflow-hidden">
      <div className="w-64 shrink-0 border-r bg-gray-100 dark:border-gray-800 dark:bg-gray-900 md:block ">
        <div className="flex h-full flex-col justify-between py-6">
          <div className="space-y-6 px-4">
            <Link className="flex items-center gap-2 font-bold" href="#">
              <BookIcon className="h-6 w-6" />
              <span>Book Overview</span>
            </Link>
            <Collapsible className="space-y-1">
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800 [&[data-state=open]>svg]:rotate-90">
                <span>Chapter 1</span>
                <ChevronRightIcon className="h-4 w-4 transition-transform" />
              </CollapsibleTrigger>
              <CollapsibleContent className="space-y-1 pl-4">
                <Link
                  className="block rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800"
                  href="#"
                >
                  Introduction
                </Link>
                <Link
                  className="block rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800"
                  href="#"
                >
                  The Basics
                </Link>
                <Link
                  className="block rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800"
                  href="#"
                >
                  Advanced Concepts
                </Link>
              </CollapsibleContent>
            </Collapsible>
            <Collapsible className="space-y-1">
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800 [&[data-state=open]>svg]:rotate-90">
                <span>Chapter 2</span>
                <ChevronRightIcon className="h-4 w-4 transition-transform" />
              </CollapsibleTrigger>
              <CollapsibleContent className="space-y-1 pl-4">
                <Link
                  className="block rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800"
                  href="#"
                >
                  Getting Started
                </Link>
                <Link
                  className="block rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800"
                  href="#"
                >
                  Intermediate Techniques
                </Link>
                <Link
                  className="block rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800"
                  href="#"
                >
                  Best Practices
                </Link>
              </CollapsibleContent>
            </Collapsible>
            <Collapsible className="space-y-1">
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800 [&[data-state=open]>svg]:rotate-90">
                <span>Chapter 3</span>
                <ChevronRightIcon className="h-4 w-4 transition-transform" />
              </CollapsibleTrigger>
              <CollapsibleContent className="space-y-1 pl-4">
                <Link
                  className="block rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800"
                  href="#"
                >
                  Troubleshooting
                </Link>
                <Link
                  className="block rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800"
                  href="#"
                >
                  Advanced Topics
                </Link>
                <Link
                  className="block rounded-md px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800"
                  href="#"
                >
                  Conclusion
                </Link>
              </CollapsibleContent>
            </Collapsible>
          </div>
          <div className="px-4">
            <Link
              className="flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:bg-gray-800"
              href="#"
            >
              <DownloadIcon className="h-4 w-4" />
              <span>Download Book</span>
            </Link>
          </div>
        </div>
      </div>
      <div className="flex-1 overflow-auto">
        <div className="mx-auto max-w-4xl px-4 py-8 md:px-6 md:py-12">
          <div className="grid gap-8">
            <div className="grid gap-4">
              <div className="flex items-center justify-between">
                <h1 className="text-3xl font-bold">Chapter 1: Introduction</h1>
                <Button
                  className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800"
                  size="icon"
                  variant="ghost"
                >
                  <MenuIcon className="h-4 w-4" />
                  <span className="sr-only">Toggle sidebar</span>
                </Button>
              </div>
              <div className="grid gap-4">
                <div className="grid gap-2 rounded-md border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
                  <div className="flex items-center justify-between">
                    <h2 className="text-xl font-semibold">Understanding the Fundamentals</h2>
                    <Link
                      className="text-sm font-medium text-primary transition-colors hover:text-primary-600 focus:text-primary-600"
                      href="#"
                    >
                      Read More
                    </Link>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    Dive into the core concepts and principles that form the foundation of this topic.
                  </p>
                </div>
                <div className="grid gap-2 rounded-md border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
                  <div className="flex items-center justify-between">
                    <h2 className="text-xl font-semibold">Exploring the Basics</h2>
                    <Link
                      className="text-sm font-medium text-primary transition-colors hover:text-primary-600 focus:text-primary-600"
                      href="#"
                    >
                      Read More
                    </Link>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    Get a comprehensive understanding of the fundamental concepts and techniques.
                  </p>
                </div>
                <div className="grid gap-2 rounded-md border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
                  <div className="flex items-center justify-between">
                    <h2 className="text-xl font-semibold">Advanced Techniques</h2>
                    <Link
                      className="text-sm font-medium text-primary transition-colors hover:text-primary-600 focus:text-primary-600"
                      href="#"
                    >
                      Read More
                    </Link>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    Explore advanced concepts and techniques to take your skills to the next level.
                  </p>
                </div>
              </div>
            </div>
            <div className="grid gap-4">
              <h1 className="text-3xl font-bold">Chapter 2: Getting Started</h1>
              <div className="grid gap-4">
                <div className="grid gap-2 rounded-md border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
                  <div className="flex items-center justify-between">
                    <h2 className="text-xl font-semibold">Setting Up Your Environment</h2>
                    <Link
                      className="text-sm font-medium text-primary transition-colors hover:text-primary-600 focus:text-primary-600"
                      href="#"
                    >
                      Read More
                    </Link>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    Learn how to set up your development environment and prepare for success.
                  </p>
                </div>
                <div className="grid gap-2 rounded-md border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
                  <div className="flex items-center justify-between">
                    <h2 className="text-xl font-semibold">Intermediate Techniques</h2>
                    <Link
                      className="text-sm font-medium text-primary transition-colors hover:text-primary-600 focus:text-primary-600"
                      href="#"
                    >
                      Read More
                    </Link>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    Explore more advanced techniques to enhance your skills and knowledge.
                  </p>
                </div>
                <div className="grid gap-2 rounded-md border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
                  <div className="flex items-center justify-between">
                    <h2 className="text-xl font-semibold">Best Practices</h2>
                    <Link
                      className="text-sm font-medium text-primary transition-colors hover:text-primary-600 focus:text-primary-600"
                      href="#"
                    >
                      Read More
                    </Link>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    Discover the best practices and guidelines to ensure success.
                  </p>
                </div>
              </div>
            </div>
            <div className="grid gap-4">
              <h1 className="text-3xl font-bold">Chapter 3: Troubleshooting</h1>
              <div className="grid gap-4">
                <div className="grid gap-2 rounded-md border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
                  <div className="flex items-center justify-between">
                    <h2 className="text-xl font-semibold">Identifying and Resolving Issues</h2>
                    <Link
                      className="text-sm font-medium text-primary transition-colors hover:text-primary-600 focus:text-primary-600"
                      href="#"
                    >
                      Read More
                    </Link>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    Learn how to effectively troubleshoot and resolve common problems.
                  </p>
                </div>
                <div className="grid gap-2 rounded-md border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
                  <div className="flex items-center justify-between">
                    <h2 className="text-xl font-semibold">Advanced Troubleshooting Techniques</h2>
                    <Link
                      className="text-sm font-medium text-primary transition-colors hover:text-primary-600 focus:text-primary-600"
                      href="#"
                    >
                      Read More
                    </Link>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    Explore advanced troubleshooting methods to tackle complex issues.
                  </p>
                </div>
                <div className="grid gap-2 rounded-md border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
                  <div className="flex items-center justify-between">
                    <h2 className="text-xl font-semibold">Conclusion</h2>
                    <Link
                      className="text-sm font-medium text-primary transition-colors hover:text-primary-600 focus:text-primary-600"
                      href="#"
                    >
                      Read More
                    </Link>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function DownloadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}
